// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_mainscreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_signal_empty_png);    // assets/Signal_Empty.png
LV_IMG_DECLARE(ui_img_signal_full_png);    // assets/Signal_Full.png
LV_IMG_DECLARE(ui_img_battery_empty_25_15_png);    // assets/Battery_Empty_25_15.png
LV_IMG_DECLARE(ui_img_battery_full_25_15_png);    // assets/Battery_Full_25_15.png
LV_IMG_DECLARE(ui_img_last_seen_png);    // assets/Last_Seen.png

// FONTS
LV_FONT_DECLARE(ui_font_Font12);
LV_FONT_DECLARE(ui_font_Font16);
LV_FONT_DECLARE(ui_font_Font48);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
