// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_mainscreen = NULL;
lv_obj_t * ui_PanelSensor = NULL;
lv_obj_t * ui_PanelSignalStrength = NULL;
lv_obj_t * ui_SliderSignalStrength = NULL;
lv_obj_t * ui_LabelSignalStrength = NULL;
lv_obj_t * ui_PanelBattery = NULL;
lv_obj_t * ui_ImageBattery = NULL;
lv_obj_t * ui_SliderBattery = NULL;
lv_obj_t * ui_LabelBattery = NULL;
lv_obj_t * ui_PanelTimePassed = NULL;
lv_obj_t * ui_ImageTimePassedTemHum = NULL;
lv_obj_t * ui_LabelTimePassedValueTemHum = NULL;
lv_obj_t * ui_PanelIndoor = NULL;
lv_obj_t * ui_LabelIndoor = NULL;
lv_obj_t * ui_PanelTemp = NULL;
lv_obj_t * ui_LabelTemp = NULL;
lv_obj_t * ui_ValueTemp = NULL;
lv_obj_t * ui_PanelHum = NULL;
lv_obj_t * ui_LabelHum = NULL;
lv_obj_t * ui_ValueHum = NULL;
lv_obj_t * ui_Attention = NULL;
lv_obj_t * ui_PanelOutdoor = NULL;
lv_obj_t * ui_LabelOutdoor = NULL;
lv_obj_t * ui_PanelExtTemp = NULL;
lv_obj_t * ui_LabelExtTemp = NULL;
lv_obj_t * ui_ValueExtTemp = NULL;
lv_obj_t * ui_LabelTitle = NULL;
// event funtions

// build funtions

void ui_mainscreen_screen_init(void)
{
    ui_mainscreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainscreen, lv_color_hex(0x303A4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainscreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSensor = lv_obj_create(ui_mainscreen);
    lv_obj_set_width(ui_PanelSensor, lv_pct(100));
    lv_obj_set_height(ui_PanelSensor, lv_pct(100));
    lv_obj_add_flag(ui_PanelSensor, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelSensor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSensor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSensor, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSensor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSensor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSignalStrength = lv_obj_create(ui_PanelSensor);
    lv_obj_set_width(ui_PanelSignalStrength, 72);
    lv_obj_set_height(ui_PanelSignalStrength, 20);
    lv_obj_set_x(ui_PanelSignalStrength, 348);
    lv_obj_set_y(ui_PanelSignalStrength, 216);
    lv_obj_set_align(ui_PanelSignalStrength, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelSignalStrength, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelSignalStrength, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelSignalStrength, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelSignalStrength, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSignalStrength, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSignalStrength, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelSignalStrength, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSignalStrength = lv_slider_create(ui_PanelSignalStrength);
    lv_slider_set_range(ui_SliderSignalStrength, -128, 16);
    lv_slider_set_value(ui_SliderSignalStrength, -60, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSignalStrength) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SliderSignalStrength, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSignalStrength, 24);
    lv_obj_set_height(ui_SliderSignalStrength, 16);
    lv_obj_set_x(ui_SliderSignalStrength, -22);
    lv_obj_set_y(ui_SliderSignalStrength, 0);
    lv_obj_set_align(ui_SliderSignalStrength, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SliderSignalStrength, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderSignalStrength, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSignalStrength, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SliderSignalStrength, &ui_img_signal_empty_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderSignalStrength, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderSignalStrength, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSignalStrength, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SliderSignalStrength, &ui_img_signal_full_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderSignalStrength, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderSignalStrength, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSignalStrength, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelSignalStrength = lv_label_create(ui_PanelSignalStrength);
    lv_obj_set_width(ui_LabelSignalStrength, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSignalStrength, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSignalStrength, 13);
    lv_obj_set_y(ui_LabelSignalStrength, -1);
    lv_obj_set_align(ui_LabelSignalStrength, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSignalStrength, "Rssi: -80");
    lv_obj_set_style_text_color(ui_LabelSignalStrength, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSignalStrength, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSignalStrength, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelBattery = lv_obj_create(ui_PanelSensor);
    lv_obj_set_width(ui_PanelBattery, 72);
    lv_obj_set_height(ui_PanelBattery, 20);
    lv_obj_set_x(ui_PanelBattery, 70);
    lv_obj_set_y(ui_PanelBattery, 216);
    lv_obj_set_align(ui_PanelBattery, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelBattery, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelBattery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelBattery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelBattery, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelBattery, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageBattery = lv_img_create(ui_PanelBattery);
    lv_img_set_src(ui_ImageBattery, &ui_img_battery_empty_25_15_png);
    lv_obj_set_width(ui_ImageBattery, 25);
    lv_obj_set_height(ui_ImageBattery, 15);
    lv_obj_set_x(ui_ImageBattery, -25);
    lv_obj_set_y(ui_ImageBattery, 0);
    lv_obj_set_align(ui_ImageBattery, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBattery, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_ImageBattery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderBattery = lv_slider_create(ui_PanelBattery);
    lv_slider_set_range(ui_SliderBattery, 2000, 4200);
    lv_slider_set_value(ui_SliderBattery, 3700, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderBattery) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderBattery, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderBattery, 25);
    lv_obj_set_height(ui_SliderBattery, 15);
    lv_obj_set_x(ui_SliderBattery, -25);
    lv_obj_set_y(ui_SliderBattery, 0);
    lv_obj_set_align(ui_SliderBattery, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SliderBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBattery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderBattery, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBattery, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBattery, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SliderBattery, &ui_img_battery_full_25_15_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderBattery, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBattery, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBattery, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelBattery = lv_label_create(ui_PanelBattery);
    lv_obj_set_width(ui_LabelBattery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBattery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBattery, 13);
    lv_obj_set_y(ui_LabelBattery, 0);
    lv_obj_set_align(ui_LabelBattery, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBattery, "3690mV");
    lv_obj_set_style_text_color(ui_LabelBattery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBattery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBattery, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTimePassed = lv_obj_create(ui_PanelSensor);
    lv_obj_set_width(ui_PanelTimePassed, 128);
    lv_obj_set_height(ui_PanelTimePassed, 20);
    lv_obj_set_x(ui_PanelTimePassed, 217);
    lv_obj_set_y(ui_PanelTimePassed, 216);
    lv_obj_set_align(ui_PanelTimePassed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelTimePassed, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelTimePassed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTimePassed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTimePassed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTimePassed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTimePassed, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelTimePassed, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelTimePassed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTimePassed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTimePassed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTimePassed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageTimePassedTemHum = lv_img_create(ui_PanelTimePassed);
    lv_img_set_src(ui_ImageTimePassedTemHum, &ui_img_last_seen_png);
    lv_obj_set_width(ui_ImageTimePassedTemHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageTimePassedTemHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageTimePassedTemHum, 1);
    lv_obj_set_y(ui_ImageTimePassedTemHum, 0);
    lv_obj_add_flag(ui_ImageTimePassedTemHum, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_ImageTimePassedTemHum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ImageTimePassedTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ImageTimePassedTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ImageTimePassedTemHum, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ImageTimePassedTemHum, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTimePassedValueTemHum = lv_label_create(ui_PanelTimePassed);
    lv_obj_set_width(ui_LabelTimePassedValueTemHum, 103);
    lv_obj_set_height(ui_LabelTimePassedValueTemHum, 16);
    lv_obj_set_x(ui_LabelTimePassedValueTemHum, 22);
    lv_obj_set_y(ui_LabelTimePassedValueTemHum, 1);
    lv_label_set_text(ui_LabelTimePassedValueTemHum, "1000: 00: 00: 00");
    lv_obj_set_style_text_color(ui_LabelTimePassedValueTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTimePassedValueTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTimePassedValueTemHum, &ui_font_Font12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelTimePassedValueTemHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelTimePassedValueTemHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelTimePassedValueTemHum, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LabelTimePassedValueTemHum, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelIndoor = lv_obj_create(ui_PanelSensor);
    lv_obj_set_width(ui_PanelIndoor, 760);
    lv_obj_set_height(ui_PanelIndoor, 215);
    lv_obj_set_x(ui_PanelIndoor, 0);
    lv_obj_set_y(ui_PanelIndoor, 50);
    lv_obj_add_flag(ui_PanelIndoor, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelIndoor, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_PanelIndoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelIndoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelIndoor = lv_label_create(ui_PanelIndoor);
    lv_obj_set_width(ui_LabelIndoor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIndoor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIndoor, 20);
    lv_obj_set_y(ui_LabelIndoor, 0);
    lv_label_set_text(ui_LabelIndoor, "Indoor");
    lv_obj_set_style_text_color(ui_LabelIndoor, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelIndoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelIndoor, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTemp = lv_obj_create(ui_PanelIndoor);
    lv_obj_set_width(ui_PanelTemp, 700);
    lv_obj_set_height(ui_PanelTemp, 60);
    lv_obj_set_x(ui_PanelTemp, 0);
    lv_obj_set_y(ui_PanelTemp, 30);
    lv_obj_add_flag(ui_PanelTemp, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTemp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelTemp, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTemp = lv_label_create(ui_PanelTemp);
    lv_obj_set_width(ui_LabelTemp, 400);
    lv_obj_set_height(ui_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelTemp, "Temperature");
    lv_obj_set_style_text_color(ui_LabelTemp, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTemp, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValueTemp = lv_label_create(ui_PanelTemp);
    lv_obj_set_width(ui_ValueTemp, 250);
    lv_obj_set_height(ui_ValueTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ValueTemp, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_ValueTemp, "120.1℃");
    lv_obj_set_style_text_color(ui_ValueTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ValueTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ValueTemp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ValueTemp, &ui_font_Font48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelHum = lv_obj_create(ui_PanelIndoor);
    lv_obj_set_width(ui_PanelHum, 700);
    lv_obj_set_height(ui_PanelHum, 60);
    lv_obj_set_x(ui_PanelHum, 0);
    lv_obj_set_y(ui_PanelHum, 120);
    lv_obj_add_flag(ui_PanelHum, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelHum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelHum, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelHum, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHum = lv_label_create(ui_PanelHum);
    lv_obj_set_width(ui_LabelHum, 400);
    lv_obj_set_height(ui_LabelHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelHum, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelHum, "Humidity");
    lv_obj_set_style_text_color(ui_LabelHum, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHum, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValueHum = lv_label_create(ui_PanelHum);
    lv_obj_set_width(ui_ValueHum, 250);
    lv_obj_set_height(ui_ValueHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ValueHum, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_ValueHum, "100%RH");
    lv_obj_set_style_text_color(ui_ValueHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ValueHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ValueHum, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ValueHum, &ui_font_Font48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Attention = lv_label_create(ui_PanelIndoor);
    lv_obj_set_width(ui_Attention, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Attention, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Attention, 50);
    lv_obj_set_y(ui_Attention, 0);
    lv_obj_set_align(ui_Attention, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Attention, "!!!!");
    lv_obj_set_style_text_color(ui_Attention, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Attention, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Attention, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Attention, &ui_font_Font48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelOutdoor = lv_obj_create(ui_PanelSensor);
    lv_obj_set_width(ui_PanelOutdoor, 760);
    lv_obj_set_height(ui_PanelOutdoor, 125);
    lv_obj_set_x(ui_PanelOutdoor, 0);
    lv_obj_set_y(ui_PanelOutdoor, 280);
    lv_obj_add_flag(ui_PanelOutdoor, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelOutdoor, LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_PanelOutdoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelOutdoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelOutdoor = lv_label_create(ui_PanelOutdoor);
    lv_obj_set_width(ui_LabelOutdoor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelOutdoor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelOutdoor, 20);
    lv_obj_set_y(ui_LabelOutdoor, 0);
    lv_label_set_text(ui_LabelOutdoor, "Outdoor");
    lv_obj_set_style_text_color(ui_LabelOutdoor, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelOutdoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelOutdoor, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelExtTemp = lv_obj_create(ui_PanelOutdoor);
    lv_obj_set_width(ui_PanelExtTemp, 700);
    lv_obj_set_height(ui_PanelExtTemp, 60);
    lv_obj_set_x(ui_PanelExtTemp, 0);
    lv_obj_set_y(ui_PanelExtTemp, 30);
    lv_obj_add_flag(ui_PanelExtTemp, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_PanelExtTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelExtTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelExtTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelExtTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelExtTemp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelExtTemp, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelExtTemp = lv_label_create(ui_PanelExtTemp);
    lv_obj_set_width(ui_LabelExtTemp, 400);
    lv_obj_set_height(ui_LabelExtTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelExtTemp, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelExtTemp, "Temperature");
    lv_obj_set_style_text_color(ui_LabelExtTemp, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelExtTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelExtTemp, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValueExtTemp = lv_label_create(ui_PanelExtTemp);
    lv_obj_set_width(ui_ValueExtTemp, 250);
    lv_obj_set_height(ui_ValueExtTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ValueExtTemp, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_ValueExtTemp, "136.1℃");
    lv_obj_set_style_text_color(ui_ValueExtTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ValueExtTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ValueExtTemp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ValueExtTemp, &ui_font_Font48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitle = lv_label_create(ui_PanelSensor);
    lv_obj_set_width(ui_LabelTitle, 400);
    lv_obj_set_height(ui_LabelTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTitle, 0);
    lv_obj_set_y(ui_LabelTitle, -5);
    lv_obj_set_align(ui_LabelTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelTitle, "LHT65N-E3");
    lv_obj_set_style_text_color(ui_LabelTitle, lv_color_hex(0x94AEB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTitle, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_mainscreen_screen_destroy(void)
{
    if(ui_mainscreen) lv_obj_del(ui_mainscreen);

    // NULL screen variables
    ui_mainscreen = NULL;
    ui_PanelSensor = NULL;
    ui_PanelSignalStrength = NULL;
    ui_SliderSignalStrength = NULL;
    ui_LabelSignalStrength = NULL;
    ui_PanelBattery = NULL;
    ui_ImageBattery = NULL;
    ui_SliderBattery = NULL;
    ui_LabelBattery = NULL;
    ui_PanelTimePassed = NULL;
    ui_ImageTimePassedTemHum = NULL;
    ui_LabelTimePassedValueTemHum = NULL;
    ui_PanelIndoor = NULL;
    ui_LabelIndoor = NULL;
    ui_PanelTemp = NULL;
    ui_LabelTemp = NULL;
    ui_ValueTemp = NULL;
    ui_PanelHum = NULL;
    ui_LabelHum = NULL;
    ui_ValueHum = NULL;
    ui_Attention = NULL;
    ui_PanelOutdoor = NULL;
    ui_LabelOutdoor = NULL;
    ui_PanelExtTemp = NULL;
    ui_LabelExtTemp = NULL;
    ui_ValueExtTemp = NULL;
    ui_LabelTitle = NULL;

}
