// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_mainscreen
extern void ui_mainscreen_screen_init(void);
extern void ui_mainscreen_screen_destroy(void);
extern lv_obj_t * ui_mainscreen;
extern lv_obj_t * ui_PanelSensor;
extern lv_obj_t * ui_PanelSignalStrength;
extern lv_obj_t * ui_SliderSignalStrength;
extern lv_obj_t * ui_LabelSignalStrength;
extern lv_obj_t * ui_PanelBattery;
extern lv_obj_t * ui_ImageBattery;
extern lv_obj_t * ui_SliderBattery;
extern lv_obj_t * ui_LabelBattery;
extern lv_obj_t * ui_PanelTimePassed;
extern lv_obj_t * ui_ImageTimePassedTemHum;
extern lv_obj_t * ui_LabelTimePassedValueTemHum;
extern lv_obj_t * ui_PanelIndoor;
extern lv_obj_t * ui_LabelIndoor;
extern lv_obj_t * ui_PanelTemp;
extern lv_obj_t * ui_LabelTemp;
extern lv_obj_t * ui_ValueTemp;
extern lv_obj_t * ui_PanelHum;
extern lv_obj_t * ui_LabelHum;
extern lv_obj_t * ui_ValueHum;
extern lv_obj_t * ui_Attention;
extern lv_obj_t * ui_PanelOutdoor;
extern lv_obj_t * ui_LabelOutdoor;
extern lv_obj_t * ui_PanelExtTemp;
extern lv_obj_t * ui_LabelExtTemp;
extern lv_obj_t * ui_ValueExtTemp;
extern lv_obj_t * ui_LabelTitle;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

